
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  web:
    build: .
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      IN_DOCKER: 1
    command: >
      sh -c "python wait_for_db.py &&
             alembic upgrade head &&
             uvicorn app.main:app --host 0.0.0.0 --port 8000"

  celery:
    build: .
    depends_on:
      - db
      - redis
    env_file: .env
    environment:
      IN_DOCKER: 1
    command: >
      sh -c "python wait_for_db.py &&
             celery -A app.celery_worker.celery_app worker --loglevel=info"

  celery-beat:
    build: .
    depends_on:
      - db
      - redis
    env_file: .env
    environment:
      IN_DOCKER: 1
    command: >
      sh -c "python wait_for_db.py &&
             celery -A app.celery_worker.celery_app beat --loglevel=info"

volumes:
  postgres_data:
