"""create raw_logs table

Revision ID: 06a8195f98e9
Revises: 
Create Date: 2025-05-23 11:50:11.798742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06a8195f98e9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('log', sa.JSON(), nullable=False),
    sa.Column('ingestion_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_logs_event_type'), 'raw_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_raw_logs_id'), 'raw_logs', ['id'], unique=False)
    op.create_index(op.f('ix_raw_logs_job_id'), 'raw_logs', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_logs_job_id'), table_name='raw_logs')
    op.drop_index(op.f('ix_raw_logs_id'), table_name='raw_logs')
    op.drop_index(op.f('ix_raw_logs_event_type'), table_name='raw_logs')
    op.drop_table('raw_logs')
    # ### end Alembic commands ###
