"""created tables

Revision ID: 84d922d1dd6e
Revises: 
Create Date: 2025-05-23 12:25:22.680918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84d922d1dd6e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('user', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('task_count', sa.Integer(), nullable=True),
    sa.Column('failed_tasks', sa.Integer(), nullable=True),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_analytics_id'), 'job_analytics', ['id'], unique=False)
    op.create_index(op.f('ix_job_analytics_job_id'), 'job_analytics', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_analytics_user'), 'job_analytics', ['user'], unique=False)
    op.create_table('raw_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('log', sa.JSON(), nullable=False),
    sa.Column('ingestion_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_logs_event_type'), 'raw_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_raw_logs_id'), 'raw_logs', ['id'], unique=False)
    op.create_index(op.f('ix_raw_logs_job_id'), 'raw_logs', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_logs_job_id'), table_name='raw_logs')
    op.drop_index(op.f('ix_raw_logs_id'), table_name='raw_logs')
    op.drop_index(op.f('ix_raw_logs_event_type'), table_name='raw_logs')
    op.drop_table('raw_logs')
    op.drop_index(op.f('ix_job_analytics_user'), table_name='job_analytics')
    op.drop_index(op.f('ix_job_analytics_job_id'), table_name='job_analytics')
    op.drop_index(op.f('ix_job_analytics_id'), table_name='job_analytics')
    op.drop_table('job_analytics')
    # ### end Alembic commands ###
