"""created tables

Revision ID: e75d5798c6bf
Revises: 
Create Date: 2025-05-23 17:36:01.367606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e75d5798c6bf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_analytics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('task_count', sa.Integer(), nullable=False),
    sa.Column('failed_tasks', sa.Integer(), nullable=False),
    sa.Column('success_rate', sa.Float(), nullable=False),
    sa.Column('insertion_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('job_id', name='uq_job_analytics_job_id')
    )
    op.create_index(op.f('ix_job_analytics_job_id'), 'job_analytics', ['job_id'], unique=True)
    op.create_index(op.f('ix_job_analytics_user'), 'job_analytics', ['user'], unique=False)
    op.create_table('raw_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event', sa.Enum('SPARK_LISTENER_JOB_START', 'SPARK_LISTENER_TASK_END', 'SPARK_LISTENER_JOB_END', name='eventtypeenum'), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('task_id', sa.String(), nullable=True),
    sa.Column('log', sa.JSON(), nullable=False),
    sa.Column('insertion_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSED', name='logstatusenum'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('job_id', 'event', 'task_id', name='uq_job_event_task')
    )
    op.create_index(op.f('ix_raw_logs_job_id'), 'raw_logs', ['job_id'], unique=False)
    op.create_index(op.f('ix_raw_logs_task_id'), 'raw_logs', ['task_id'], unique=False)
    op.create_index(op.f('ix_raw_logs_user'), 'raw_logs', ['user'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_logs_user'), table_name='raw_logs')
    op.drop_index(op.f('ix_raw_logs_task_id'), table_name='raw_logs')
    op.drop_index(op.f('ix_raw_logs_job_id'), table_name='raw_logs')
    op.drop_table('raw_logs')
    op.drop_index(op.f('ix_job_analytics_user'), table_name='job_analytics')
    op.drop_index(op.f('ix_job_analytics_job_id'), table_name='job_analytics')
    op.drop_table('job_analytics')
    # ### end Alembic commands ###
